### ISSUE TITLE
最近在搞什么坑？

### ISSUE THREAD

**Issue by xhacker** [Cee/ama#4]

**Comment by Cee** [comment]
1. Reading
   - [Programming iOS 9](http://shop.oreilly.com/product/0636920044352.do)
   - Ruby 元编程
2. Coding
   - [1024404](http://1024404.com)：前端改版，等待上线
   - DanmuFM（a.k.a Miyu）：iOS 音乐弹幕电台（完整地用 Swift 做一个小应用）
3. Designing
   - 98 Days Icon Redesign
4. Exams
   - 明日还有一场 GRE /w\
